const assert=require('node:assert/strict');
const Database=require('better-sqlite3');
const {createStore}=require('../../server/lib/ab-store');
const {createHistory,pageSlug}=require('../../server/lib/ab-history');
const db=new Database(':memory:');
db.exec(`CREATE TABLE landing_pages(id INTEGER PRIMARY KEY,name TEXT,slug TEXT,template_type TEXT,ab_config TEXT);
 CREATE TABLE settings(key TEXT,value TEXT); INSERT INTO settings VALUES ('timezone','America/New_York');
 CREATE TABLE activity_logs(id INTEGER PRIMARY KEY,entity_type TEXT,entity_id INTEGER,details TEXT,created_at TEXT);
 CREATE TABLE visitors(id INTEGER PRIMARY KEY,eli_clickid TEXT UNIQUE,landing_page TEXT,ab_variant TEXT,first_visit TEXT,last_visit TEXT);
 CREATE TABLE leads(id INTEGER PRIMARY KEY,landing_page_id INTEGER,ab_variant TEXT,hidden_fields TEXT,created_at TEXT,eli_clickid TEXT);`);
const page=(id,name,slug,cfg)=>db.prepare('INSERT INTO landing_pages VALUES (?,?,?,?,?)').run(id,name,slug,'join',JSON.stringify(cfg));
page(7,'MCA test','test',{enabled:true,split:80,variantB_page:38});
page(12,'Previous B','old-b',{enabled:true,split:50,variantB:{}});
page(38,'September B','new-b',{});
page(1,'Ended test','ended',{enabled:false});
const log=(page,details,at)=>db.prepare("INSERT INTO activity_logs(entity_type,entity_id,details,created_at) VALUES ('ab_test',?,?,?)").run(page,details+' A/B test on page',at);
log(7,'Enabled','2026-04-07 11:37:39');log(7,'Enabled','2026-09-01 10:25:41');log(12,'Enabled','2026-03-04 15:10:55');log(1,'Enabled','2026-03-26 12:00:00');log(1,'Disabled','2026-04-03 20:00:00');
const v=(id,slug,variant,at,first=at)=>db.prepare('INSERT INTO visitors VALUES (?,?,?,?,?,?)').run(id,'visitor-'+id,slug,variant,first,at);
v(1,'/lp/test/','B','2026-08-01 12:00:00','2026-02-01 00:00:00');
v(2,'/lp/test/','A','2026-09-02 12:00:00');v(3,'/lp/test/',null,'2026-09-02 13:00:00');v(4,'/lp/test/?utm_source=meta','B','2026-09-02 14:00:00');
v(5,'/lp/new-b/','B','2026-09-02 14:00:00');v(6,'/lp/old-b/','A','2026-09-02 14:00:00');
v(7,'/lp/test/',null,'2026-04-06 12:00:00');v(8,'/lp/test/',null,'2026-09-29 09:00:00','2026-09-02 14:00:00');
v(9,'/lp/test-suffix/','B','2026-09-02 14:00:00');v(10,'/lp/test/',null,'2026-08-01 12:00:00');
v(11,'/lp/old-b/',null,'2026-09-02 14:00:00');v(12,'https://other.test/lp/test/','B','2026-09-02 14:00:00');
const lead=(id,page,variant,url,at,visitor)=>db.prepare('INSERT INTO leads VALUES (?,?,?,?,?,?)').run(id,page,variant,JSON.stringify(url?{page_url:url}:{}),at,visitor?'visitor-'+visitor:'');
lead(101,12,'B','https://info.coastaldebt.com/lp/test/','2026-08-01 12:00:00',1);
lead(102,38,'B','https://info.coastaldebt.com/lp/test/?x=1','2026-09-02 14:01:00',4);
lead(103,7,'', 'https://info.coastaldebt.com/lp/test/','2026-09-02 13:01:00',3);
lead(104,38,'B','https://info.coastaldebt.com/lp/new-b/','2026-09-02 14:01:00',5);
lead(105,12,'B','https://info.coastaldebt.com/lp/old-b/','2026-09-02 14:01:00',6);
lead(106,7,'A','https://info.coastaldebt.com/lp/test/','2026-09-29 09:01:00',8);
lead(107,7,'','https://info.coastaldebt.com/lp/test/','2026-04-06 12:00:00',7);
lead(108,12,'B',null,'2026-08-01 12:00:00',1); // Could be the source of parent test 7: unresolved.
lead(109,38,'B','https://info.coastaldebt.com/lp/test/','2026-09-01 10:25:41',4); // Exact run boundary.
lead(110,38,'B','https://other.test/lp/test/','2026-09-02 14:01:00',4);
const cutoff=Date.parse('2026-09-29T08:10:54.321Z');
const store=createStore(db,()=>cutoff);store.syncAll();
const history=createHistory(db);history.importOnce();
const report=history.report({page:7});
const current=report.runs.find(r=>r.id===report.selectedId);
assert.equal(current.config.split,80);
assert.equal(current.b_name,'September B');
assert.equal(current.stats.A.visitors,2);assert.equal(current.stats.A.inferredVisitors,1);
assert.equal(current.stats.A.leads,1);assert.equal(current.stats.A.inferredLeads,1);
assert.equal(current.stats.B.visitors,1);assert.equal(current.stats.B.leads,2);
assert.equal(current.stats.B.rate,null,'Incomplete historical denominators cannot produce a >100% rate');
assert.equal(current.excluded_updated_visitors,1);
const earlier=report.runs.find(r=>r.page_id===7 && r.id!==current.id);
assert.equal(earlier.config.split,null,'Never invent an old allocation');
assert.equal(earlier.b_name,'Previous B');
assert.equal(earlier.stats.B.leads,1);assert.equal(earlier.stats.A.inferredVisitors,1);
const direct=report.runs.find(r=>r.page_id===12);
assert.equal(direct.stats.B.leads,1,'Parent test B leads must not count on the source page test');
assert.equal(direct.stats.U.leads,1,'Missing origin on a shared source remains unresolved');
assert.equal(direct.stats.U.visitors,1);
const day=history.report({page:7,from:'2026-09-02',to:'2026-09-02'});
assert.equal(day.runs.find(r=>r.id===current.id).stats.B.leads,1,'Filter lead submission date');
assert.equal(day.daily.length,1);assert.equal(day.daily[0].date,'2026-09-02');
assert.ok(report.runs.some(r=>r.page_id===1),'Preserve disabled tests in history');
assert.equal(db.prepare('SELECT COUNT(*) n FROM leads').get().n,10,'Do not change source records');
const before=JSON.stringify(history.report({page:7}));
db.prepare("UPDATE visitors SET last_visit='2026-10-01 00:00:00',ab_variant='A' WHERE id=4").run();
history.importOnce();assert.equal(JSON.stringify(history.report({page:7})),before,'Import is immutable and idempotent');
assert.equal(pageSlug('/lp/test/index.html?x=1'),'test');
assert.equal(pageSlug('https://other.test/lp/test/'),null);
assert.equal(db.prepare('SELECT COUNT(*) n FROM ab_participants').get().n,0,'History must not fabricate live exposures');
console.log('PASS: historical periods, changing B sources, original lead URLs, direct B exclusion, inferred/unknown attribution, cutoff, date filters, no fabricated splits, and immutable/idempotent recovery.');

const overview=require('../../server/lib/ab-report').report;
store.history=history;
page(99,'New test','new-test',{enabled:true,split:50});
page(100,'Newer ended test','ended-live',{enabled:true,split:50});
store.syncAll();
db.prepare('UPDATE landing_pages SET ab_config=? WHERE id=100').run(JSON.stringify({enabled:false}));
store.syncAll();
const all=overview(store);
assert.equal(all.source,'all');
assert.equal(all.runs[0].page_id,99,'A new active test appears first, even before any visits');
assert.equal(all.selectedId,all.runs[0].id,'Default details follow the first active test');
assert.equal(all.runs[0].stats.A.visitors+all.runs[0].stats.B.visitors,0);
assert.equal(all.activeCount,3);
assert.equal(all.historicalCount,report.runs.length);
assert.equal(new Set(all.runs.map(r=>r.id)).size,all.runs.length,'Live and historical run IDs remain distinct');
assert.ok(all.runs.some(r=>r.source==='historical'));
assert.deepEqual(all.daily,[],'Zero-traffic new test must not inherit historical daily results');
const selectedHistory=overview(store,{run:current.id,from:'2026-09-02',to:'2026-09-02'});
assert.deepEqual(selectedHistory.daily,day.daily);
assert.deepEqual(selectedHistory.recent,day.recent);
assert.equal(selectedHistory.runs.find(r=>r.id===selectedHistory.selectedId).source,'historical');
const livePage=overview(store,{page:7});
assert.ok(livePage.selectedId>0,'Page deep links select the current live run first');
assert.equal(livePage.daily.length,0);
const historyOnly=overview(store,{source:'historical',page:7});
assert.ok(historyOnly.runs.every(r=>r.source==='historical'));
assert.equal(historyOnly.activeCount,3,'Historical view still knows that current tests exist');
assert.equal(historyOnly.selectedId,current.id);
assert.deepEqual(historyOnly.daily,history.report({page:7}).daily);
const liveOnly=overview(store,{source:'live'});
assert.ok(liveOnly.runs.every(r=>r.source==='live'));
assert.equal(liveOnly.selectedId,all.selectedId);
const historicalDates=overview(store,{from:'2026-09-01',to:'2026-09-02'});
assert.ok(historicalDates.runs.some(r=>r.page_id===99),'Date filters change metrics, not test visibility');
assert.throws(()=>overview(store,{from:'2026-10-02',to:'2026-10-01'}),/Start date/);
assert.equal(JSON.stringify(history.report({page:7})),before,'Unified overview never changes historical results');
console.log('PASS: all-tests overview, active-first ordering, zero-traffic tests, source filters, signed run IDs, correct live/historical details and date ranges, and immutable historical results.');
